server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ms-estoque
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

broker:
  queue:
    email:
      name: default.email
