-- liquibase formatted sql

--changeset Luiz:20250106-02-01
INSERT INTO users (name, user_name, email, password, phone_number, cpf, active, version, created_at)
VALUES ('ADMIN', 'admin', 'admin@exemplo.com',
        '$2a$10$lSrI2h./WOgFdyM7vkO9..gq50bfPluo0HyAHA7ySVldjaYCERMpu', '00000000000', '00000000000',true, 0, now());

-- changeset Luiz:20250106-02-02
INSERT INTO items (name, description, price, active, version, created_at)
VALUES
    ('BANANA', 'Banana', '3.00', true,  0,now()),
    ('BOLACHA', 'Bolacha', '5.50', true, 0,now()),
    ('MACA', 'Maçã', '4.00', true, 0,now()),
    ('ARROZ', 'Arroz', '20.00', true, 0,now()),
    ('FEIJAO', 'Feijão', '15.00', true, 0,now()),
    ('LEITE', 'Leite', '4.50', true, 0,now()),
    ('PAO', 'Pão', '2.00', true, 0,now()),
    ('AZEITE', 'Azeite', '12.00', true, 0,now()),
    ('QUEIJO', 'Queijo', '25.00', true, 0,now()),
    ('MANTEIGA', 'Manteiga', '8.00', false, 0,now()),
    ('CERVEJA', 'Cerveja', '3.00', true, 0,now()),
    ('SABONETE', 'Sabonete', '1.50', true, 0,now()),
    ('DESINFETANTE', 'Desinfetante', '5.00', true, 0,now()),
    ('LIMAO', 'Limão', '2.00', true, 0,now()),
    ('CENOURA', 'Cenoura', '3.00', true, 0,now()),
    ('BATATA', 'Batata', '4.00', false, 0,now()),
    ('ALFACE', 'Alface', '3.50', true, 0,now()),
    ('TOMATE', 'Tomate', '6.00', true, 0,now()),
    ('PEITO DE FRANGO', 'Peito de Frango', '20.00', false, 0,now()),
    ('CARNE MOIDA', 'Carne Moída', '25.00', true, 0,now()),
    ('LINGUIÇA', 'Linguiça', '15.00', true, 0,now()),
    ('OVO', 'Ovo', '8.00', true, 0,now()),
    ('AÇUCAR', 'Açúcar', '5.00', true, 0,now()),
    ('CACHORRO QUENTE', 'Cachorro Quente', '10.00', true, 0,now()),
    ('PIZZA', 'Pizza', '30.00', true, 0,now()),
    ('HAMBURGUER', 'Hamburguer', '12.00', true, 0,now()),
    ('BATATA FRITA', 'Batata Frita', '8.00', true, 0,now()),
    ('MAIONESE', 'Maionese', '4.50', true, 0,now()),
    ('KETCHUP', 'Ketchup', '3.00', true, 0,now()),
    ('MUSTARDA', 'Mostarda', '3.00', true, 0,now()),
    ('ALHO', 'Alho', '5.00', true, 0,now()),
    ('CEBOLA', 'Cebola', '4.00', true, 0,now()),
    ('REQUEIJÃO', 'Requeijão', '8.00', true, 0,now()),
    ('CREME DE LEITE', 'Creme de leite', '6.00', true, 0,now()),
    ('YOGURTE', 'Iogurte', '5.00', false, 0,now()),
    ('BEBIDA ENERGÉTICA', 'Bebida Energética', '7.00', true, 0,now()),
    ('AGUA', 'Água', '1.00', true, 0,now()),
    ('JUIZA', 'Suco', '4.00', true, 0,now()),
    ('PRESUNTO', 'Presunto', '12.00', true, 0,now()),
    ('TUBO DE CREME', 'Creme Dental', '3.00', true, 0,now()),
    ('DESODORANTE', 'Desodorante', '8.00', true, 0,now()),
    ('XAMPU', 'Shampoo', '10.00', true, 0,now()),
    ('CONDICIONADOR', 'Condicionador', '9.00', true, 0,now()),
    ('BALDE', 'Balde', '15.00', true, 0,now()),
    ('ESFREGÃO', 'Esfregão', '7.00', true, 0,now()),
    ('VASSOURA', 'Vassoura', '10.00', true, 0,now()),
    ('RODO', 'Rodo', '6.00', true, 0,now()),
    ('PANO DE CHÃO', 'Pano de Chão', '5.00', true, 0,now()),
    ('LIMPADOR', 'Limpador', '4.00', true, 0,now()),
    ('MOPA', 'Mopa', '18.00', false, 0,now()),
    ('LIXO', 'Lixeira', '12.00', true, 0,now()),
    ('PASTA DE DENTES', 'Pasta de Dentes', '4.00', true, 0,now()),
    ('LIMPEZA', 'Produtos de Limpeza', '20.00', true, 0,now()),
    ('CALCIO', 'Suplemento de Cálcio', '25.00', true, 0,now()),
    ('VITAMINA C', 'Vitamina C', '18.00', true, 0,now()),
    ('GASES', 'Gás', '60.00', false, 0,now()),
    ('PAPEL HIGIENICO', 'Papel Higiênico', '15.00', true, 0,now()),
    ('TOALHA DE PAPEL', 'Toalha de Papel', '10.00', true, 0,now()),
    ('GUARDANAPO', 'Guardanapo', '3.00', true, 0,now()),
    ('LIMPADOR DE VIDRO', 'Limpador de Vidro', '6.00', true, 0,now()),
    ('PIROGA', 'Pizza Piroga', '28.00', true, 0,now()),
    ('BATATA DOCE', 'Batata Doce', '6.00', true, 0,now()),
    ('FEIJAO PRETO', 'Feijão Preto', '18.00', true, 0,now()),
    ('FEIJAO BRANCO', 'Feijão Branco', '17.00', true, 0,now()),
    ('CENTEIO', 'Centeio', '20.00', true, 0,now()),
    ('ALMEIRIM', 'Almeirim', '12.00', true, 0,now()),
    ('MOLHO', 'Molho', '4.50', true, 0,now()),
    ('PIPOCAS', 'Pipocas', '5.50', true, 0,now()),
    ('CHOCOLATE', 'Chocolate', '9.00', true, 0,now()),
    ('DOCE', 'Doce', '6.50', true, 0,now()),
    ('BISCOITO', 'Biscoito', '4.00', true, 0,now()),
    ('PRATO', 'Prato', '2.00', true, 0,now()),
    ('GARRAFA', 'Garrafa', '3.00', true, 0,now()),
    ('MESA', 'Mesa', '50.00', true, 0,now()),
    ('CADEIRA', 'Cadeira', '40.00', true, 0,now()),
    ('SOFA', 'Sofá', '250.00', true, 0,now()),
    ('GUARDARROPA', 'Guarda-roupa', '350.00', true, 0,now()),
    ('CAMA', 'Cama', '300.00', true, 0,now()),
    ('PISO', 'Piso', '70.00', false, 0,now()),
    ('LAMPADEIRO', 'Lâmpada', '5.00', true, 0,now()),
    ('TAPETE', 'Tapete', '30.00', true, 0,now()),
    ('JOGO DE CAMA', 'Jogo de Cama', '80.00', true, 0,now()),
    ('TACO', 'Taco', '6.00', true, 0,now()),
    ('JOGO DE TALHERES', 'Jogo de Talheres', '15.00', true, 0,now()),
    ('TAÇA', 'Taça', '10.00', true, 0,now()),
    ('VITRINE', 'Vitrine', '100.00', true, 0,now()),
    ('BRINQUEDO', 'Brinquedo', '20.00', true, 0,now()),
    ('LIVRO', 'Livro', '30.00', true, 0,now()),
    ('REVISTA', 'Revista', '7.00', true, 0,now()),
    ('CADERNO', 'Caderno', '10.00', true, 0,now()),
    ('CANETA', 'Caneta', '2.00', true, 0,now()),
    ('LAPIS', 'Lápis', '1.50', true, 0,now()),
    ('BORRACHA', 'Borracha', '1.00', true, 0,now()),
    ('FITA', 'Fita', '4.00', true, 0,now()),
    ('ESTOJO', 'Estojo', '8.00', true, 0,now()),
    ('MOCHILA', 'Mochila', '40.00', true, 0,now()),
    ('CELULAR', 'Celular', '1200.00', true, 0,now()),
    ('TELEVISÃO', 'Televisão', '1500.00', true, 0,now()),
    ('NOTEBOOK', 'Notebook', '2500.00', true, 0,now()),
    ('CARREGADOR', 'Carregador', '50.00', true, 0,now()),
    ('FONE DE OUVIDO', 'Fone de Ouvido', '80.00', true, 0,now()),
    ('MOUSE', 'Mouse', '20.00', true, 0,now()),
    ('TECLADO', 'Teclado', '30.00', true, 0,now());
